python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PO-0-1_1.fa PO-0-1_1 3
python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PO-0-1_2.fa PO-0-1_2 3
python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PO-1-1_1.fa PO-1-1_1 3
python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PO-1-1_2.fa PO-1-1_2 3
python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PO-2-1_1.fa PO-2-1_1 3
python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PO-2-1_2.fa PO-2-1_2 3
python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PO-4-1_1.fa PO-4-1_1 3
python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PO-4-1_2.fa PO-4-1_2 3
python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PR-0-1_1.fa PR-0-1_1 3
python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PR-0-1_2.fa PR-0-1_2 3
python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PR-1-1_1.fa PR-1-1_1 3
python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PR-1-1_2.fa PR-1-1_2 3
python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PR-2-1_1.fa PR-2-1_1 3
python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PR-2-1_2.fa PR-2-1_2 3
python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PR-3-1_1.fa PR-3-1_1 3
python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PR-3-1_2.fa PR-3-1_2 3
python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PR-3-1-N_1.fa PR-3-1-N_1 3
python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PR-3-1-N_2.fa PR-3-1-N_2 3
python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PY-0-1_1.fa PY-0-1_1 3
python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PY-0-1_2.fa PY-0-1_2 3
python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PY-1-1_1.fa PY-1-1_1 3
python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PY-1-1_2.fa PY-1-1_2 3
python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PY-2-1_1.fa PY-2-1_1 3
python /BiO/sgpark/MetagenomePipeline/TaxonomyProfiling.py ../00.RawData/PY-2-1_2.fa PY-2-1_2 3
